SELECT 
    STUDENTID     AS "Roll Number",
    NAME          AS "Student Name",
    DATEOFBIRTH   AS "Date of Birth",
    GENDER        AS "Gender",
    CONTACTNUMBER AS "Contact Number",
    DEPARTMENTID  AS "Department ID"
FROM STUDENT;

SELECT 
    STUDENTID    AS Roll_No,
    NAME         AS Student_Name,
    DEPARTMENTID AS Dept_ID
FROM STUDENT;

SELECT 
    FACULTYID   AS "Faculty ID",
    NAME        AS "Faculty Name",
    DESIGNATION AS "Designation",
    EMAIL       AS "Email Address"
FROM FACULTY;

SELECT 
    COURSEID     AS "Course ID",
    COURSENAME   AS "Course Name",
    CREDITS      AS "Credit Hours",
    DEPARTMENTID AS "Department ID",
    FACULTYID    AS "Faculty ID"
FROM COURSE;

SELECT 
    STUDENTID AS "Roll Number",
    COURSEID  AS "Course ID",
    SEMESTER  AS "Semester",
    GRADE     AS "Grade"
FROM ENROLLMENT;

SELECT * FROM STUDENT WHERE DEPARTMENTID = 101;
SELECT * FROM STUDENT WHERE GENDER = 'Female';
SELECT * FROM FACULTY WHERE DESIGNATION = 'Assistant Professor';
SELECT * FROM FACULTY WHERE DEPARTMENTID = 102;
SELECT * FROM COURSE WHERE CREDITS >= 4;
SELECT * FROM STUDENT WHERE DATEOFBIRTH > DATE '2003-01-01';
SELECT * FROM ENROLLMENT WHERE SEMESTER = '4';

SELECT * FROM STUDENT ORDER BY NAME ASC;
SELECT * FROM STUDENT ORDER BY DATEOFBIRTH DESC;
SELECT * FROM FACULTY ORDER BY DESIGNATION ASC;
SELECT * FROM COURSE ORDER BY CREDITS DESC;
SELECT * FROM STUDENT FETCH FIRST 3 ROWS ONLY;
SELECT * FROM COURSE FETCH FIRST 5 ROWS ONLY;

SELECT NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, DATEOFBIRTH)/12) AS AGE FROM STUDENT;
SELECT COURSENAME, CREDITS + 1 AS UPDATED_CREDITS FROM COURSE;
SELECT COURSENAME, CREDITS + 1 AS UPDATED_CREDITS FROM COURSE;
SELECT STUDENTID, COURSEID, SEMESTER, GRADE AS FINAL_GRADE FROM ENROLLMENT;
SELECT NAME, EXTRACT(YEAR FROM DATEOFBIRTH) AS BIRTH_YEAR FROM STUDENT;
SELECT NAME, SUBSTR(EMAIL, INSTR(EMAIL,'@')+1) AS EMAIL_DOMAIN FROM FACULTY;

